#!/bin/bash
# tests/test_bonus.sh
# Teste Rápido dos Bónus: Dashboard, VHosts e Keep-Alive
# Necessário correr "./server" num terminal antes de executar este script.

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
SERVER_URL="http://localhost:8080"

echo "=========================================="
echo "   TESTE DE BÓNUS (OPCIONAIS)"
echo "=========================================="

# 0. Preparação (Garantir que os sites existem)
mkdir -p www/site1 www/site2
echo "<h1>Site 1 - Bonus</h1>" > www/site1/index.html
echo "<h1>Site 2 - Bonus</h1>" > www/site2/index.html

# ---------------------------------------------------------
# TESTE 1: Dashboard (/stats)
# ---------------------------------------------------------
echo -n "1. Testing Dashboard (/stats)... "
HTTP_CODE=$(curl -s -o /tmp/stats_output.html -w "%{http_code}" "$SERVER_URL/stats")
if [ "$HTTP_CODE" -eq 200 ] && grep -q "Server Dashboard" /tmp/stats_output.html; then
    echo -e "${GREEN}[ PASS ]${NC}"
else
    echo -e "${RED}[ FAIL ]${NC} (Code: $HTTP_CODE ou conteúdo incorreto)"
fi

# ---------------------------------------------------------
# TESTE 2: Virtual Hosts
# ---------------------------------------------------------
echo -n "2. Testing Virtual Host (site1.local)... "
CONTENT=$(curl -s -H "Host: site1.local" "$SERVER_URL/index.html")
if [[ "$CONTENT" == *"Site 1 - Bonus"* ]]; then
    echo -e "${GREEN}[ PASS ]${NC}"
else
    echo -e "${RED}[ FAIL ]${NC} (Recebido: $CONTENT)"
fi

echo -n "3. Testing Virtual Host (site2.local)... "
CONTENT=$(curl -s -H "Host: site2.local" "$SERVER_URL/index.html")
if [[ "$CONTENT" == *"Site 2 - Bonus"* ]]; then
    echo -e "${GREEN}[ PASS ]${NC}"
else
    echo -e "${RED}[ FAIL ]${NC} (Recebido: $CONTENT)"
fi

# ---------------------------------------------------------
# TESTE 3: Keep-Alive
# ---------------------------------------------------------
echo -n "4. Testing Keep-Alive Header... "
# Verifica se o header Connection: keep-alive está presente na resposta
HEADER=$(curl -s -I "$SERVER_URL/index.html" | grep -i "Connection: keep-alive")
if [ -n "$HEADER" ]; then
    echo -e "${GREEN}[ PASS ]${NC}"
else
    echo -e "${RED}[ FAIL ]${NC} (Header não encontrado ou é 'close')"
fi

# ---------------------------------------------------------
# TESTE 4: Range Requests (HTTP 206)
# ---------------------------------------------------------
echo -n "5. Testing Range Requests (bytes=0-10)... "

# Faz o pedido e guarda o output e os headers
# -D - : faz dump dos headers para stdout
# -o ... : guarda o corpo num ficheiro
curl -s -D /tmp/headers_range.txt -o /tmp/body_range.txt -H "Range: bytes=0-10" "$SERVER_URL/index.html"

# Verificar se o código HTTP é 206 (Partial Content)
if grep -q "HTTP/1.1 206" /tmp/headers_range.txt; then
    # Verificar se o Content-Length é 11 (bytes 0 a 10 = 11 bytes)
    if grep -q "Content-Length: 11" /tmp/headers_range.txt; then
        echo -e "${GREEN}[ PASS ]${NC}"
    else
        echo -e "${RED}[ FAIL ]${NC} (Status 206 OK, mas Content-Length incorreto)"
        cat /tmp/headers_range.txt
    fi
else
    echo -e "${RED}[ FAIL ]${NC} (Esperado 206, recebido outro status)"
    head -n 1 /tmp/headers_range.txt
fi

# Limpeza
rm -f /tmp/headers_range.txt /tmp/body_range.txt

# ---------------------------------------------------------
# TESTE 5: CGI Script (Python)
# ---------------------------------------------------------
echo -n "6. Testing CGI Script Execution (test_cgi.py)... "

# 1. Criar um script Python de teste
cat > www/test_cgi.py << 'EOF'
print("<h1>CGI Works!</h1>")
print("<p>Dynamic content generated by Python.</p>")
EOF

# 2. Fazer o pedido ao servidor
# Esperamos receber o output do print() do Python
CONTENT=$(curl -s "$SERVER_URL/test_cgi.py")

# 3. Validar
if [[ "$CONTENT" == *"CGI Works!"* ]] && [[ "$CONTENT" == *"Dynamic content"* ]]; then
    echo -e "${GREEN}[ PASS ]${NC}"
else
    echo -e "${RED}[ FAIL ]${NC} (Conteúdo incorreto ou erro 500)"
    echo "Recebido: $CONTENT"
fi

# Limpeza do ficheiro temporário
rm -f www/test_cgi.py

echo ""
echo "Teste concluído."
rm -f /tmp/stats_output.html